SlnParkingControl/src/ParkingControl.Web/Models/ErrorViewModel.cs
namespace ParkingControl.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SlnParkingControl/src/ParkingControl.Web/Models/VeiculosViewModel.cs
using ParkingControl.Domain.DTOs;

namespace ParkingControl.Web.Models
{
    public class VeiculosViewModel
    {
        public List<VeiculoDTO> Veiculos { get; set; }
        public List<TarifaDTO> Tarifas { get; set; }
    }
}

SlnParkingControl/src/ParkingControl.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ParkingControl.Application.Service.IServices;
using ParkingControl.Domain.DTOs;
using ParkingControl.Domain.Enums;

namespace ParkingControl.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IVeiculoService _veiculoService;
        private readonly ITarifaService _tarifaService;

        public HomeController(IVeiculoService veiculoService, ITarifaService tarifaService)
        {
            _veiculoService = veiculoService;
            _tarifaService = tarifaService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _veiculoService.BuscarTodos();
            var tarifas = await _tarifaService.BuscarTodas();

            foreach (var item in result)
            {
                var tarifa = tarifas
                    .Where(t => t.dataInicioVigencia.Year == item.dataHoraEntrada.Year)
                    .Select(t => t.preco)
                    .FirstOrDefault();

                if (tarifa <= 0)
                {
                    item.Mensagem = $"Não há tarifa cadastrada para o período {item.dataHoraEntrada.Year}.";
                    item.ClasseTipoAlerta = item.RetornarTipoAlerta(TipoAlerta.Warning);
                }
                item.tarifa = tarifa;

                if (item.dataHoraSaida.HasValue)
                {
                    item.duracao = _veiculoService.RetornarDuracao(item.dataHoraEntrada, item.dataHoraSaida.Value);
                    item.tempoCobrado = _veiculoService.CalcularTempoCobradoEmHoras(item.dataHoraEntrada, item.dataHoraSaida.Value);
                    item.valorPagar = _veiculoService.CalcularValorPagar(item.dataHoraEntrada, item.dataHoraSaida.Value, tarifa);
                }
            }

            return View(result);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("id,placa,dataHoraEntrada")] VeiculoDTO veiculo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (veiculo.dataHoraEntrada > veiculo.dataHoraSaida)
                    {
                        veiculo.Mensagem = "Data início não pode ser maior que a data fim.";
                        return View(veiculo);
                    }

                    if (await _veiculoService.Salvar(veiculo) > 0)
                        return RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                veiculo.Mensagem = ex.Message;
                veiculo.ClasseTipoAlerta = veiculo.RetornarTipoAlerta(TipoAlerta.Danger);
                return View(veiculo);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var result = await _veiculoService.BuscarPeloId(id);
                return View(result);
            }
            catch (Exception e)
            {
                var veiculo = new VeiculoDTO();
                veiculo.Mensagem = e.Message;
                veiculo.ClasseTipoAlerta = veiculo.RetornarTipoAlerta(TipoAlerta.Danger);

                return View(veiculo);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("id,placa,dataHoraEntrada,dataHoraSaida")] VeiculoDTO veiculo)
        {
            try
            {
                if (id != veiculo.id)
                {
                    veiculo.Mensagem = "Ocorreu um erro ao buscar o registro no banco de dados.";
                    veiculo.ClasseTipoAlerta = veiculo.RetornarTipoAlerta(TipoAlerta.Warning);
                    return View(veiculo);
                }

                if (await _veiculoService.Editar(veiculo) > 0)
                    return RedirectToAction(nameof(Index));

            }
            catch (Exception e)
            {
                veiculo.Mensagem = e.Message;
                veiculo.ClasseTipoAlerta = veiculo.RetornarTipoAlerta(TipoAlerta.Danger);
                return View(veiculo);
            }

            return View(veiculo);
        }

        [HttpPost]
        public async Task<IActionResult> Search(string placa)
        {
            try
            {
                var tarifas = await _tarifaService.BuscarTodas();
                var result = await _veiculoService.BuscarPorPlaca(placa);

                foreach (var item in result)
                {
                    var tarifa = tarifas
                    .Where(t => t.dataInicioVigencia.Year == item.dataHoraEntrada.Year)
                    .Select(t => t.preco)
                    .FirstOrDefault();

                    if (tarifa <= 0)
                    {
                        item.Mensagem = "Não há tarifa cadastrada para o período!";
                        item.ClasseTipoAlerta = item.RetornarTipoAlerta(TipoAlerta.Warning);
                    }
                    item.tarifa = tarifa;

                    if (item.dataHoraSaida.HasValue)
                    {
                        item.duracao = _veiculoService.RetornarDuracao(item.dataHoraEntrada, item.dataHoraSaida.Value);
                        item.tempoCobrado = _veiculoService.CalcularTempoCobradoEmHoras(item.dataHoraEntrada, item.dataHoraSaida.Value);
                        item.valorPagar = _veiculoService.CalcularValorPagar(item.dataHoraEntrada, item.dataHoraSaida.Value, tarifa);
                    }
                }

                return View(result);
            }
            catch (Exception e)
            {
                var veiculo = new VeiculoDTO();
                veiculo.Mensagem = e.Message;
                veiculo.ClasseTipoAlerta = veiculo.RetornarTipoAlerta(TipoAlerta.Danger);
                return View(veiculo);
            }
        }
    }
}

SlnParkingControl/src/ParkingControl.Web/Controllers/TarifaController.cs
using Microsoft.AspNetCore.Mvc;
using ParkingControl.Application.Service.IServices;
using ParkingControl.Domain.DTOs;
using ParkingControl.Domain.Enums;

namespace ParkingControl.Web.Controllers
{
    public class TarifaController : Controller
    {
        private readonly ITarifaService _tarifaService;

        public TarifaController(ITarifaService tarifaService)
        {
            _tarifaService = tarifaService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var result = await _tarifaService.BuscarTodas();
                return View(result);
            }
            catch (Exception ex)
            {
                var tarifa = new TarifaDTO();
                tarifa.Mensagem = ex.Message;
                tarifa.ClasseTipoAlerta = tarifa.RetornarTipoAlerta(TipoAlerta.Danger);
                return View(tarifa);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("id,placa,dataHoraEntrada")] TarifaDTO tarifaDTO)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (tarifaDTO.dataInicioVigencia > tarifaDTO.dataFimVigencia)
                    {
                        tarifaDTO.Mensagem = "Data início não pode ser maior que a data fim.";
                        return View(tarifaDTO);
                    }

                    if (await _tarifaService.Salvar(tarifaDTO) > 0) 
                        return RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                tarifaDTO.Mensagem = ex.Message;
                tarifaDTO.ClasseTipoAlerta = tarifaDTO.RetornarTipoAlerta(TipoAlerta.Danger);
                return View(tarifaDTO);
            }
        }
    }
}

SlnParkingControl/src/ParkingControl.Web/Views/Home/Create.cshtml
@model ParkingControl.Domain.DTOs.VeiculoDTO

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Registrar</h5>
        </div>
        <div>
            <span>
                @if (Model != null && !string.IsNullOrEmpty(Model.Mensagem))
                {
                    <div class="@Model.ClasseTipoAlerta" role="alert">
                        <p>@Model.Mensagem</p>
                    </div>
                }
            </span>
        </div>
        <form asp-action="Create" novalidate>
            <div class="modal-body">
                <div class="form-floating mb-3">
                    <input asp-for="placa" type="text" class="form-control" id="floatingInput" placeholder="Placa" required>
                    <label for="floatingInput">Placa</label>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="dataHoraEntrada" class="form-control" id="floatingInput" placeholder="Data e hora entrada" required>
                    <label for="floatingInput">Data e hora entrada</label>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-outline-success" type="submit">Salvar</button>
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </form>
    </div>
</div>

SlnParkingControl/src/ParkingControl.Web/Views/Home/Details.cshtml
@model ParkingControl.Domain.DTOs.VeiculoDTO

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Editar @Model.placa</h5>
        </div>
        <div class="modal-body">
            <p>Modal body text goes here.</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary">Salvar</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        </div>
    </div>
</div>

SlnParkingControl/src/ParkingControl.Web/Views/Home/Edit.cshtml
@model ParkingControl.Domain.DTOs.VeiculoDTO

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Editar @Model.placa</h5>
        </div>
        <div>
            <span>
                @if (Model != null && !string.IsNullOrEmpty(Model.Mensagem))
                {
                    <div class="alert alert-warning" role="alert">
                        <p>@Html.DisplayFor(modelItem => Model.Mensagem)</p>
                    </div>
                }
            </span>
        </div>
        <form asp-action="Edit">
            <div class="modal-body">
                <input type="hidden" asp-for="id" />
                <div class="form-floating mb-3">
                    <input asp-for="placa" type="text" class="form-control" id="floatingInput" placeholder="Placa" required />
                    <label for="floatingInput">Placa</label>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="dataHoraEntrada" class="form-control" id="floatingInput" placeholder="Data e hora entrada" required />
                    <label for="floatingInput">Data e hora entrada</label>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="dataHoraSaida" class="form-control" id="floatingInput" placeholder="Data e hora saída" />
                    <label for="floatingInput">Data e hora saída</label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-outline-primary">Salvar</button>
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </form>
    </div>
</div>

SlnParkingControl/src/ParkingControl.Web/Views/Home/Index.cshtml
@model IEnumerable<ParkingControl.Domain.DTOs.VeiculoDTO>

<div class="card rounded shadow-sm p-3">
    <div class="d-flex justify-content-between mb-3">
        <div class="align-items-end flex-column">
            <form asp-action="Search">
                <div class="input-group ms-auto">
                    <div class="input-group-prepended">
                        <input name="placa" type="text" class="form-control" placeholder="AAA0000 / AAA2B23">
                    </div>
                    <button type="submit" class="btn btn-outline-primary">Buscar placa</button>
                </div>
            </form>
        </div>
        <a onclick="create()" class="btn btn-outline-success">Marcar Entrada</a>
    </div>

    <div>
        <span>
            @foreach (var v in Model)
            {
                @if (!string.IsNullOrEmpty(v.Mensagem))
                {
                    <div class="@v.ClasseTipoAlerta" role="alert">
                        <p>@v.Mensagem</p>
                    </div>
                }
            }
        </span>
    </div>

    <table class="table table-striped table-hover">
        <thead>
            <tr class="text-center">
                <th>@Html.DisplayNameFor(model => model.placa)</th>
                <th>@Html.DisplayNameFor(model => model.dataHoraEntrada)</th>
                <th>@Html.DisplayNameFor(model => model.dataHoraSaida)</th>
                <th>@Html.DisplayNameFor(model => model.duracao)</th>
                <th>@Html.DisplayNameFor(model => model.tempoCobrado)</th>
                <th>@Html.DisplayNameFor(model => model.tarifa)</th>
                <th>@Html.DisplayNameFor(model => model.valorPagar)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var v in Model)
            {
                <tr onclick="edit(@v.id)" class="linha-tabela text-center">
                    <td>@Html.DisplayFor(modelItem => v.placa)</td>
                    <td>@Html.DisplayFor(modelItem => v.dataHoraEntrada)</td>
                    <td>@Html.DisplayFor(modelItem => v.dataHoraSaida)</td>
                    <td>@Html.DisplayFor(modelItem => v.duracao)</td>
                    <td>@Html.DisplayFor(modelItem => v.tempoCobrado)</td>
                    <td>R$ @Html.DisplayFor(modelItem => v.tarifa)</td>
                    <td>R$ @Html.DisplayFor(modelItem => v.valorPagar)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal" id="modal" tabindex="-1"></div>

@section scripts {
    <script>
        const edit = (id) => {
            $('#modal').load(`@Url.Action("Edit")/${id}`, () => {
                $('#modal').modal('show');
            })
        }

        const create = () => {
            $('#modal').load(`@Url.Action("Create")`, () => {
                $('#modal').modal('show');
            })
        }
    </script>
}

SlnParkingControl/src/ParkingControl.Web/Views/Home/Search.cshtml
@model IEnumerable<ParkingControl.Domain.DTOs.VeiculoDTO>

<div class="card rounded shadow-sm p-3">
    <div class="d-flex justify-content-between mb-3">
        <div class="align-items-end flex-column">
            <form>
                <div class="input-group ms-auto">
                    <div class="input-group-prepended">
                        <input type="text" class="form-control" placeholder="AAA0000 / AAA2B23">
                    </div>
                    <button class="btn btn-outline-primary">Buscar placa</button>
                </div>
            </form>
        </div>
        <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index">Página Inicial</a>
    </div>
    <div>
        <span>
            @foreach (var v in Model)
            {
                @if (!string.IsNullOrEmpty(v.Mensagem))
                {
                    <div class="@v.ClasseTipoAlerta" role="alert">
                        <p>@v.Mensagem</p>
                    </div>
                }
            }
        </span>
    </div>
    <table class="table table-striped table-hover">
        <thead>
            <tr class="text-center">
                <th>@Html.DisplayNameFor(model => model.placa)</th>
                <th>@Html.DisplayNameFor(model => model.dataHoraEntrada)</th>
                <th>@Html.DisplayNameFor(model => model.dataHoraSaida)</th>
                <th>@Html.DisplayNameFor(model => model.duracao)</th>
                <th>@Html.DisplayNameFor(model => model.tempoCobrado)</th>
                <th>@Html.DisplayNameFor(model => model.tarifa)</th>
                <th>@Html.DisplayNameFor(model => model.valorPagar)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var v in Model)
            {
                <tr onclick="edit(@v.id)" class="linha-tabela text-center">
                    <td>@Html.DisplayFor(modelItem => v.placa)</td>
                    <td>@Html.DisplayFor(modelItem => v.dataHoraEntrada)</td>
                    <td>@Html.DisplayFor(modelItem => v.dataHoraSaida)</td>
                    <td>@Html.DisplayFor(modelItem => v.duracao)</td>
                    <td>@Html.DisplayFor(modelItem => v.tempoCobrado)</td>
                    <td>R$ @Html.DisplayFor(modelItem => v.tarifa)</td>
                    <td>R$ @Html.DisplayFor(modelItem => v.valorPagar)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal" id="modal" tabindex="-1"></div>

@section scripts {
    <script>
        const edit = (id) => {
            $('#modal').load(`@Url.Action("Edit")/${id}`, () => {
                $('#modal').modal('show');
            })
        }

        const create = () => {
            $('#modal').load(`@Url.Action("Create")`, () => {
                $('#modal').modal('show');
            })
        }
    </script>
}

SlnParkingControl/src/ParkingControl.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Parking Control</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ParkingControl.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/img/logo-parking.png" id="logo-navbar" class="me-1" />Parking Control
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarifa" asp-action="Index">Tarifas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="ms-3">
            &copy; 2023 - Parking Control - Desenvolvido por <a href="https://github.com/Cxavier14" target="_blank">Eduardo Xavier</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SlnParkingControl/src/ParkingControl.Web/Views/Tarifa/Create.cshtml
@model ParkingControl.Domain.DTOs.TarifaDTO

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Registrar</h5>
        </div>
        <div>
            <span>
                @if (Model != null && !string.IsNullOrEmpty(Model.Mensagem))
                {
                    <div class="@Model.ClasseTipoAlerta" role="alert">
                        <p>@Model.Mensagem</p>
                    </div>
                }
            </span>
        </div>
        <form asp-action="Create" novalidate>
            <div class="modal-body">
                <div class="form-floating mb-3">
                    <input asp-for="dataInicioVigencia" type="text" class="form-control" id="floatingInput" placeholder="01/01/2000" required>
                    <label for="floatingInput">Placa</label>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="dataFimVigencia" class="form-control" id="floatingInput" placeholder="01/01/2000" required>
                    <label for="floatingInput">Data e hora entrada</label>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="preco" class="form-control" id="floatingInput" placeholder="R$ 0,00" required>
                    <label for="floatingInput">Preço</label>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-outline-success" type="submit">Salvar</button>
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </form>
    </div>
</div>

SlnParkingControl/src/ParkingControl.Web/Views/Tarifa/Edit.cshtml
@model ParkingControl.Domain.DTOs.TarifaDTO

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Editar @Model.id</h5>
        </div>
        <div>
            <span>
                @if (Model != null && !string.IsNullOrEmpty(Model.Mensagem))
                {
                    <div class="@Model.ClasseTipoAlerta" role="alert">
                        <p>@Model.Mensagem</p>
                    </div>
                }
            </span>
        </div>
        <form asp-action="Edit">
            <div class="modal-body">
                <input type="hidden" asp-for="id" />
                <div class="form-floating mb-3">
                    <input asp-for="dataInicioVigencia" type="text" class="form-control" id="floatingInput" placeholder="01/01/2000" required />
                    <label for="floatingInput">Data inicial</label>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="dataFimVigencia" class="form-control" id="floatingInput" placeholder="01/01/2000" required />
                    <label for="floatingInput">Data fim</label>
                </div>
                <div class="form-floating mb-3">
                    <input asp-for="preco" class="form-control" id="floatingInput" placeholder="R$ 0,00" required />
                    <label for="floatingInput">Preço</label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-outline-primary">Salvar</button>
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </form>
    </div>
</div>

SlnParkingControl/src/ParkingControl.Web/Views/Tarifa/Index.cshtml
@model IEnumerable<ParkingControl.Domain.DTOs.TarifaDTO>

@{
    ViewData["Title"] = "Tarifas";
}

<div class="card rounded shadow-sm p-3">
    <div class="d-flex justify-content-between mb-3">
        <div class="align-items-end flex-column">
            <form asp-action="Search">
                <div class="input-group ms-auto">
                    <div class="input-group-prepended">
                        <input name="tarifa" type="text" class="form-control" placeholder="">
                    </div>
                    <button type="submit" class="btn btn-outline-primary">Buscar tarifa</button>
                </div>
            </form>
        </div>
        <a onclick="create()" class="btn btn-outline-success">Marcar Entrada</a>
    </div>

    <div>
        <span>
            @foreach (var v in Model)
            {
                @if (!string.IsNullOrEmpty(v.Mensagem))
                {
                    <div class="@v.ClasseTipoAlerta" role="alert">
                        <p>@v.Mensagem</p>
                    </div>
                }
            }
        </span>
    </div>

    <table class="table table-striped table-hover">
        <thead>
            <tr class="text-center">
                <th>@Html.DisplayNameFor(model => model.dataInicioVigencia)</th>
                <th>@Html.DisplayNameFor(model => model.dataFimVigencia)</th>
                <th>@Html.DisplayNameFor(model => model.preco)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var v in Model)
            {
                <tr onclick="edit(@v.id)" class="linha-tabela text-center">
                    <td>@Html.DisplayFor(modelItem => v.dataInicioVigencia)</td>
                    <td>@Html.DisplayFor(modelItem => v.dataFimVigencia)</td>
                    <td>@Html.DisplayFor(modelItem => v.preco)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal" id="modal" tabindex="-1"></div>

@section scripts {
    <script>
        const edit = (id) => {
            $('#modal').load(`@Url.Action("Edit")/${id}`, () => {
                $('#modal').modal('show');
            })
        }

        const create = () => {
            $('#modal').load(`@Url.Action("Create")`, () => {
                $('#modal').modal('show');
            })
        }
    </script>
}